/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Variable;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author YOJHAN
 */
public class ventana_variables extends javax.swing.JFrame {
    private ventana_principal v;
    private ArrayList<Variable> List_variables;
    /**
     * Creates new form ventana_variables
     */
    public ventana_variables(ventana_principal v) {
        initComponents();
        this.v = v;
        this.setLocationRelativeTo(null);
        llenarCampos();
    }
    
    private void llenarCampos(){
       List_variables = v.getList_variables();
       jTextField0.setText(""+List_variables.get(0).getValorInicial());
       jTextField1.setText(""+List_variables.get(1).getValorInicial());
       jTextField2.setText(""+List_variables.get(2).getValorInicial());
       jTextField3.setText(""+List_variables.get(3).getValorInicial());
       jTextField4.setText(""+List_variables.get(4).getValorInicial());
       jTextField5.setText(""+List_variables.get(5).getValorInicial());
       jTextField6.setText(""+List_variables.get(6).getValorInicial());
       jTextField7.setText(""+List_variables.get(7).getValorInicial());
       jTextField8.setText(""+List_variables.get(8).getValorInicial());
       jTextField9.setText(""+List_variables.get(24).getValorInicial());
       jTextField10.setText(""+List_variables.get(26).getValorInicial());
       jTextField11.setText(""+List_variables.get(27).getValorInicial());
       jTextField12.setText(""+List_variables.get(36).getValorInicial());
       jTextField13.setText(""+List_variables.get(37).getValorInicial());
       jTextField14.setText(""+List_variables.get(38).getValorInicial());
       jTextField15.setText(""+List_variables.get(39).getValorInicial());
       jTextField16.setText(""+List_variables.get(40).getValorInicial());
       jTextField17.setText(""+List_variables.get(41).getValorInicial());
       jTextField18.setText(""+List_variables.get(42).getValorInicial());
       jTextField19.setText(""+List_variables.get(43).getValorInicial());
       jTextField20.setText(""+List_variables.get(44).getValorInicial());
       jTextField21.setText(""+List_variables.get(45).getValorInicial());
       jTextField22.setText(""+List_variables.get(46).getValorInicial());
       jTextField23.setText(""+List_variables.get(47).getValorInicial());
       jTextField24.setText(""+List_variables.get(33).getValorInicial());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField0 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Modificar variables");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Definir valores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, 30));

        jLabel2.setText("Cantidad personal médico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Discapacitados atendidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Disp. Empleo Accesible");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setText("Empleo Accesible");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setText("Población Participando Com.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel7.setText("Necesidad Atención");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel8.setText("Total población");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel9.setText("Total población discapacitada");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel11.setText("Demanda Personal médico");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel12.setText("Interés Sociedad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel13.setText("Tasa personas adquieren disc");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        jLabel14.setText("Tasa defuncion med");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel15.setText("Tasa calidad relaciones");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jLabel16.setText("Promedio Amistad");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel17.setText("Tasa Calidad Educacion");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel18.setText("Tasa desarrollo");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jLabel19.setText("Tasa empleados disc");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        jLabel20.setText("Tasa Ambiente Laboral");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLabel21.setText("Discapacitados atendidos");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel22.setText("Tasa Nacimiento Discapacidad");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jLabel23.setText("Tasa defuncion disc");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel24.setText("Tasa Nacimientos sin discapacidad");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel37.setText("Instituciones accesibles");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel38.setText("Cantidad defunciones");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 110, -1));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 110, -1));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 110, -1));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 110, -1));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 110, -1));
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 110, -1));
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 110, -1));
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 110, -1));
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 110, -1));
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 110, -1));
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 110, -1));
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 110, -1));
        getContentPane().add(jTextField0, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 110, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 110, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 110, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 110, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 110, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 110, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 110, -1));

        jLabel39.setText("Porcentaje Eficiencia Metodos");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 110, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        jLabel10.setText("           ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        String ObjButtons[] = {"Cerrar","Cancelar"};
        int PromptResult = JOptionPane.showOptionDialog(this, 
        "Si cierra esta ventana, los cambios en las variables no quedarán guardados", "Atención", 
        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, 
        ObjButtons,ObjButtons[1]);
        if(PromptResult==0){
        this.dispose();  
        v.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        List_variables.get(0).setValorInicial(Double.parseDouble(jTextField0.getText()));
        List_variables.get(1).setValorInicial(Double.parseDouble(jTextField1.getText()));
        List_variables.get(2).setValorInicial(Double.parseDouble(jTextField2.getText()));
        List_variables.get(3).setValorInicial(Double.parseDouble(jTextField3.getText()));
        List_variables.get(4).setValorInicial(Double.parseDouble(jTextField4.getText()));
        List_variables.get(5).setValorInicial(Double.parseDouble(jTextField5.getText()));
        List_variables.get(6).setValorInicial(Double.parseDouble(jTextField6.getText()));
        List_variables.get(7).setValorInicial(Double.parseDouble(jTextField7.getText()));
        List_variables.get(8).setValorInicial(Double.parseDouble(jTextField8.getText()));
        List_variables.get(24).setValorInicial(Double.parseDouble(jTextField9.getText()));
        List_variables.get(26).setValorInicial(Double.parseDouble(jTextField10.getText()));
        List_variables.get(27).setValorInicial(Double.parseDouble(jTextField11.getText()));
        List_variables.get(33).setValorInicial(Double.parseDouble(jTextField24.getText()));
        List_variables.get(36).setValorInicial(Double.parseDouble(jTextField12.getText()));
        List_variables.get(37).setValorInicial(Double.parseDouble(jTextField13.getText()));
        List_variables.get(38).setValorInicial(Double.parseDouble(jTextField14.getText()));
        List_variables.get(39).setValorInicial(Double.parseDouble(jTextField15.getText()));
        List_variables.get(40).setValorInicial(Double.parseDouble(jTextField16.getText()));
        List_variables.get(41).setValorInicial(Double.parseDouble(jTextField17.getText()));
        List_variables.get(42).setValorInicial(Double.parseDouble(jTextField18.getText()));
        List_variables.get(43).setValorInicial(Double.parseDouble(jTextField19.getText()));
        List_variables.get(44).setValorInicial(Double.parseDouble(jTextField20.getText()));
        List_variables.get(45).setValorInicial(Double.parseDouble(jTextField21.getText()));
        List_variables.get(46).setValorInicial(Double.parseDouble(jTextField22.getText()));
        List_variables.get(47).setValorInicial(Double.parseDouble(jTextField23.getText()));
                                        
        this.dispose();  
        v.setEnabled(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Asigne valores válidos","Información",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField0;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
